name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    services:
      postgres-1:
        image: postgres:12.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db_test
        ports:
          - 55322:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1, 8.2, 8.3 ]
        stability: [ prefer-stable ]
        experimental: [ false ]
        include:
          - php: 8.3
            stability: prefer-stable
            experimental: true

    name: PHP ${{ matrix.php }} - L${{ matrix.laravel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        if: "${{ matrix.experimental == false }}"
        run: |
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Install dependencies (experimental)
        if: "${{ matrix.experimental == true }}"
        run: |
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Execute tests (Unit and Feature)
        run: vendor/bin/phpunit

      - name: Static analysis with PHPStan
        run: vendor/bin/phpstan analyse

      - name: Static analysis with Psalm
        if: "${{ matrix.experimental == false }}"
        run: vendor/bin/psalm

      - name: Coding style PSR12 Check
        run: vendor/bin/phpcs
